### ISSUE TITLE
Meta ai jailbreak is not working

### ISSUE THREAD

**Issue by asciibene** [BlackTechX011/HacxGPT-Jailbreak-prompts#1]

**Comment by BlackTechX011** [comment]
# @asciibene 
this first version of this jailbreak prompt so this may not work in chat as normal or DAN (for chatGPT)  jailbreaks work.
# so How to use?
u can use this tool by using it as system prompt. U can use it as system prompt as many GUI app like LM studio provides or any other web ui like [huggingface.co](https://huggingface.co/chat/) does so u can directly put this jailbreak prompt as system prompt. 
## go try the above way and have fun 
# later I will made a YouTube video for this

**Comment by asciibene** [comment]
oh damn Im using meta.ai through the messenger app :/ so I guess I cant input system prompts
